### ISSUE TITLE
General Comments Megathread #1

### ISSUE THREAD

**Issue by SophieWalden** [8BitToaster/Block-Tower-Defense#1]
Since no one has written any issues concerning bugs that are in my game (Used to a few a day, but this game I worked harder to make sure there are fewer bugs), I've taken the liberty to start a mega-thread.

Comment what you want, it could be about literally anything. Strategy, opinions, or even just information you would like to hear from me. I'll make sure to reply to everything people comment in here.

-8BitToaster

**Comment by THB0705** [comment]
Hey man, it's been a while!

Here are some comments on your tower defense business:
-When I start the game it puts me at wave 200 right away, this should be wave 1 right?
-I understand that when you test the game you want to have a lot of cash and stuff but for me as a downloader, I doubt that I am supposed to start with 750,000 units?
-It is also very tricky for me to figure out what each tower does as there is no text whatsoever...
-You have a two buttons at the bottom of the screen but this is how they look...
![Capture1](https://user-images.githubusercontent.com/42702031/70723513-4cd9d480-1cf9-11ea-9a2b-04fdb5b31e36.PNG)

There are a lot more comments but I think if you fix the above issues the program will become much more clear to me already and allow me to look at your program's details more closely. But yea, right now, I don't get what's going on at all...

-THB

P.S. I would really advise working with multiples files instead of having a 1000+ line main file. This would clear things up a lot. For example you could make a file for the monsters, for the towers. Etc. use them in the main file instead. Right now it is impossible for me to truly understand parts of your code in one go if I would try to help find an issue.

**Comment by SophieWalden** [comment]
Hey, long time no see!

Sorry, this game has a bit of a mess, I was working on it the side during college finals week, but now I have a break from college so I can work on this more. 

Things I've done:
Fixed the waves and cash
Added the names for each tower right about how much each tower cost
Split the main.py into 3 separate files for easier access

I'm planning on adding a tutorial soon and also adding little info things to show what each upgrade does for the towers. If you were wondering what the buttons were doing on the bottom the big one starts the rounds/speed it up to 2 times speed and the small one makes it go on autoplay which starts a new round whenever the old one ends.

Gonna try to fix up this mess I made

-8BitToaster

**Comment by THB0705** [comment]
**Part 1**
When I get home, I am going to actually try playing the game. However for now looking at the code, I have a few more organisational tips for structure and clarity:

- Perhaphs make a wave.py file where you define all the waves and stuff, right now that's just a big chunk of clutter in your main.py file (121-270, that's like 150 lines). Doing that will just make your structure tons better and clearer.

- In addition, be sure to add as many comments as you can explaining what the code does and where it does it. This helps both people like me but also yourself in understanding the code better and seeing bottlenecks and where it can be optimimsed / clarified.

- Don't forget to update your changelog and readme file by the way ;) . The readme file for sure is outdated.

-THB

P.S. Right now it's still a small project (C++) in early phase, but could you star my FlashCard project, it would be nice if you could test it in a few days (right now it's boring).

**Comment by THB0705** [comment]
**Part 2**
I just played the game. Here are some comments:

- Please fill the buttons with symbols that are maybe toned down and then when clicked they highlight. It's kind of weird having empty buttons right now.

- Consider saving the user's data so that on the next play they can choose to continue or restart.

- Add a start menu where saves can be opened and settings can be tweaked.

- Consider making the monsters come in different shapes as well, not just different colours. Same goes for the towers, add different shapes. Or if you really want to, add some pixelated art, but this may be a lot of work.

-THB

**Comment by SophieWalden** [comment]
Okay, I will split the wave.py into a different file and I'm working on updating my changelog. The save/main menu features are in the works and I'll work on different shapes (That's actually a pretty good idea).

I just added some art for darts and shurikens and whatnot, but I'm going to work on tower images soon. 

Also, I checked out your flashcards and despite my not being able to run it (Due to only have mac/linux machines), I checked out the code and it seems pretty good. I can try to boot up some windows vm eventually, but I'll do that later.

-8BitToaster

**Comment by THB0705** [comment]
In addition to adding monster and tower sprites. Consider adding a heart sprite for the user's lives left and a dollar or bill sprite for the amount of money the user has during the game.

Plus, as it stands now I find the game to be quite difficult already around wave 10, is that on purpose?
