### ISSUE TITLE
Is putting in sprites bad?

### ISSUE THREAD

**Issue by SophieWalden** [8BitToaster/Block-Tower-Defense#3]
Related to a comment I got before on another website stating that with the addition of adding the flamethrower sprite in it feels like it's throwing off the blocky-ness of the game. I was just wondering any more feedback on this, should I continue to add sprites in the game or does everyone just want the towers to be different colored squares?

-8BitToaster

**Comment by THB0705** [comment]
Considering your whole block theme it makes sense. However instead of making sophisticated sprites you could make simple sprites whose shape is comprised of smaller blocks. This allows for the user to be able to distinguish towers not just by colour but also by shape. I get that blocky-ness is a big part of the game right now. However, I would personally advise against sticking to the block theme so much.
