### ISSUE TITLE
Freeze Tower

### ISSUE THREAD

**Issue by THB0705** [8BitToaster/Block-Tower-Defense#6]
I've been playing the game a bit now but I feel like the freeze tower is too weak. It doesn't add much early game value at all. Consider tweaking it perhaps? It's up to you Toaster.

**Comment by SophieWalden** [comment]
I agree. I've always used it as a later-game tower, but without me having an easier mode yet where late game is more accessible, I've been thinking about buffing it a bit. The whole "Easier mode" thing will be available in an update soon so that may be nice, but I've messed around with the ice tower for now.

What I did was I gave it the ability to pop monsters at level 0, I've made it so it happens around 30% slower than usual towers because it can hit every monster in its range. I tried it out and now if you do something like an ice-dart combo it's actually semi-viable.

-8BitToaster
